// /* Delete it
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 optimized-room.glb 
// */

// import React, { useEffect, useState } from "react";
// import { useTexture } from "@react-three/drei";
// import * as THREE from "three";
// import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

// const FallbackRoom = () => (
//   <group>
//     <mesh>
//       <boxGeometry args={[3, 2.4, 1.8]} />
//       <meshStandardMaterial color="#1d4ed8" metalness={0.2} roughness={0.3} />
//     </mesh>
//     <mesh position={[0, 0.8, 0.95]}>
//       <boxGeometry args={[2.2, 1.2, 0.1]} />
//       <meshStandardMaterial color="#93c5fd" emissive="#2563eb" emissiveIntensity={0.25} />
//     </mesh>
//     <mesh position={[0, -0.2, 0.2]}>
//       <boxGeometry args={[0.8, 0.5, 0.4]} />
//       <meshStandardMaterial color="#f8fafc" />
//     </mesh>
//   </group>
// );

// export function Room(props) {
//   const [gltf, setGltf] = useState(null);
//   const [hasLoadError, setHasLoadError] = useState(false);
//   const matcapTexture = useTexture("/images/textures/mat1.png");

//   useEffect(() => {
//     let isMounted = true;
//     const loader = new GLTFLoader();

//     loader.load(
//       "/models/optimized-room.glb",
//       (loadedModel) => {
//         if (isMounted) {
//           setGltf(loadedModel);
//           setHasLoadError(false);
//         }
//       },
//       undefined,
//       () => {
//         if (isMounted) {
//           setHasLoadError(true);
//           setGltf(null);
//         }
//       }
//     );

//     return () => {
//       isMounted = false;
//     };
//   }, []);

//   const curtainMaterial = new THREE.MeshPhongMaterial({
//     color: "#d90429",
//   });

//   const bodyMaterial = new THREE.MeshPhongMaterial({
//     map: matcapTexture,
//   });

//   const tableMaterial = new THREE.MeshPhongMaterial({
//     color: "#582f0e",
//   });

//   const radiatorMaterial = new THREE.MeshPhongMaterial({
//     color: "#fff",
//   });

//   const compMaterial = new THREE.MeshStandardMaterial({
//     color: "#fff",
//   });

//   const pillowMaterial = new THREE.MeshPhongMaterial({
//     color: "#8338ec",
//   });

//   const chairMaterial = new THREE.MeshPhongMaterial({
//     color: "#000",
//   });

//   if (!gltf || hasLoadError) {
//     return (
//       <group {...props} dispose={null}>
//         <FallbackRoom />
//       </group>
//     );
//   }

//   const { nodes, materials } = gltf;

//   const renderMesh = (nodeName, material, props = {}) => {
//     const geometry = nodes?.[nodeName]?.geometry;
//     if (!geometry) return null;

//     return <mesh key={nodeName} geometry={geometry} material={material} {...props} />;
//   };

//   return (
//     <group {...props} dispose={null}>
//       {renderMesh("_________6_blinn1_0", curtainMaterial)}
//       {renderMesh("body1_blinn1_0", bodyMaterial)}
//       {renderMesh("cabin_blinn1_0", tableMaterial)}
//       {renderMesh("chair_body_blinn1_0", chairMaterial)}
//       {renderMesh("comp_blinn1_0", compMaterial)}
//       {renderMesh("emis_lambert1_0", materials?.lambert1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("handls_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("keyboard_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("kovrik_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("lamp_bl_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("lamp_white_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("miuse_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("monitor2_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("monitor3_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("pCylinder5_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("pillows_blinn1_0", pillowMaterial)}
//       {renderMesh("polySurface53_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("radiator_blinn1_0", radiatorMaterial)}
//       {renderMesh("radiator_blinn1_0001", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("railing_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("red_bttns_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("red_vac_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("stylus_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("table_blinn1_0", tableMaterial)}
//       {renderMesh("tablet_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("triangle_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("vac_black_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("vacuum1_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("vacuumgrey_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("vires_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("window_blinn1_0", materials?.blinn1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//       {renderMesh("window4_phong1_0", materials?.phong1 || new THREE.MeshStandardMaterial({ color: "#fff" }))}
//     </group>
//   );
// }
